################################################################################
##                                    bits
##
## This file is distributed under the 3-clause Berkeley Software Distribution
## License. See LICENSE for details.
################################################################################
os: linux
dist: focal
language: cpp
git:
  depth: 1

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -V

jobs:
  include:
    #################################################################################
    # Code coverage
    #################################################################################
    - os: linux
      name: Code coverage
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - lcov
      env:
        - CC=gcc-10
        - CXX=g++-10
      script:
        - mkdir build                        || travis_terminate 1
        - cd build                           || travis_terminate 1
        - cmake .. -DBITS_CODE_COVERAGE=ON   || travis_terminate 1
        - make -j9 code-coverage-all         || travis_terminate 1
        - ../scripts/uploadCoverage.sh       || travis_terminate 1

    #################################################################################
    # Linux / GCC
    #################################################################################
    # gcc 11
    - os: linux
      name: Linux / gcc 11
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-11
      env:
        - CC=gcc-11
        - CXX=g++-11
    # gcc 10
    - os: linux
      name: Linux / gcc 10
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-10
      env:
        - CC=gcc-10
        - CXX=g++-10
    # gcc 9
    - os: linux
      name: Linux / gcc 9
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9
    # gcc 8
    - os: linux
      name: Linux / gcc 8
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-8
      env:
        - CC=gcc-8
        - CXX=g++-8
    # gcc 7
    - os: linux
      name: Linux / gcc 7
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

    #################################################################################
    # Linux / clang
    #################################################################################
    # clang 13
    - os: linux
      name: Linux / clang 13
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-13
            - g++-10
      env:
        - CC=clang-13
        - CXX=clang++-13
    # clang 12
    - os: linux
      name: Linux / clang 12
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-12
            - g++-10
      env:
        - CC=clang-12
        - CXX=clang++-12
    # clang 11
    - os: linux
      name: Linux / clang 11
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-11
            - g++-9
      env:
        - CC=clang-11
        - CXX=clang++-11
    # clang 10
    - os: linux
      name: Linux / clang 10
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - g++-9
      env:
        - CC=clang-10
        - CXX=clang++-10
    # clang 9
    - os: linux
      name: Linux / clang 9
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - g++-9
      env:
        - CC=clang-9
        - CXX=clang++-9
    # clang 8
    - os: linux
      name: Linux / clang 8
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - g++-9
      env:
        - CC=clang-8
        - CXX=clang++-8
    # clang 7
    - os: linux
      name: Linux / clang 7
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - g++-9
      env:
        - CC=clang-7
        - CXX=clang++-7
    # clang 6.0
    - os: linux
      name: Linux / clang 6.0
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url:    'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - g++-9
      env:
        - CC=clang-6.0
        - CXX=clang++-6.0

    #################################################################################
    # macosx
    #################################################################################
    # osx (xcode 12.2)
    - os: osx
      name: macOs / xcode 12.2
      osx_image: xcode12.2
    # osx (xcode 11)
    - os: osx
      name: macOs / xcode 11
      osx_image: xcode11
    # osx (xcode 10.2)
    - os: osx
      name: macOs / xcode 10.2
      osx_image: xcode10.2
