////////////////////////////////////////////////////////////////////////////////
//                                    bits
//
// This file is distributed under the 3-clause Berkeley Software Distribution
// License. See LICENSE for details.
////////////////////////////////////////////////////////////////////////////////
#ifndef BITS_DETAIL_HELPER_MACROS_H
#define BITS_DETAIL_HELPER_MACROS_H

#include <bits/BitsTraits.h>
#include <string_view>

//-----------------------------------------------------------------------------
//- Internal helper macros
//-----------------------------------------------------------------------------

// Namespaces
#define __BITS_EMPTY_NAMESPACE
#define __BITS_BEGIN_NAMESPACE(nameSpace)  namespace nameSpace {
#define __BITS_END_NAMESPACE(nameSpace)    }; // namespace nameSpace

// Enum size() free standaing function
#define __BITS_ENUM_DECLARE_SIZE(nameSpace, name, ...) \
template<> inline constexpr size_t size<nameSpace name>(void) { return __BITS_NUM_ARGS(__VA_ARGS__) / 2u; }

// Enum to string_view free standing function
#define __BITS_ENUM_DECLARE_TO_STRING(nameSpace, name, ...) \
inline constexpr std::string_view to_string(nameSpace name value) { \
    switch(value) { \
        __BITS_ENUM_DECLARE_ALL_TO_STRING_VALUES(nameSpace, name, __VA_ARGS__) \
    } \
    return "<invalid>"; \
}
#define __BITS_ENUM_DECLARE_ALL_TO_STRING_VALUES(nameSpace, name, ...)  __BITS_RECURSE_SINGLE(__BITS_ENUM_DECLARE_TO_STRING_VALUE, , nameSpace, name, __VA_ARGS__)
#define __BITS_ENUM_DECLARE_TO_STRING_VALUE(nameSpace, name, val)       case nameSpace name::val : return #val;

// Arguments count
#define __BITS_NUM_ARGS(...) __BITS_NUM_ARGS2(__VA_ARGS__, 512, 511, 510, 509, 508, 507, 506, 505, 504, 503, 502, 501, 500, 499, 498, 497, 496, 495, 494, 493, 492, 491, 490, 489, 488, 487, 486, 485, 484, 483, 482, 481, 480, 479, 478, 477, 476, 475, 474, 473, 472, 471, 470, 469, 468, 467, 466, 465, 464, 463, 462, 461, 460, 459, 458, 457, 456, 455, 454, 453, 452, 451, 450, 449, 448, 447, 446, 445, 444, 443, 442, 441, 440, 439, 438, 437, 436, 435, 434, 433, 432, 431, 430, 429, 428, 427, 426, 425, 424, 423, 422, 421, 420, 419, 418, 417, 416, 415, 414, 413, 412, 411, 410, 409, 408, 407, 406, 405, 404, 403, 402, 401, 400, 399, 398, 397, 396, 395, 394, 393, 392, 391, 390, 389, 388, 387, 386, 385, 384, 383, 382, 381, 380, 379, 378, 377, 376, 375, 374, 373, 372, 371, 370, 369, 368, 367, 366, 365, 364, 363, 362, 361, 360, 359, 358, 357, 356, 355, 354, 353, 352, 351, 350, 349, 348, 347, 346, 345, 344, 343, 342, 341, 340, 339, 338, 337, 336, 335, 334, 333, 332, 331, 330, 329, 328, 327, 326, 325, 324, 323, 322, 321, 320, 319, 318, 317, 316, 315, 314, 313, 312, 311, 310, 309, 308, 307, 306, 305, 304, 303, 302, 301, 300, 299, 298, 297, 296, 295, 294, 293, 292, 291, 290, 289, 288, 287, 286, 285, 284, 283, 282, 281, 280, 279, 278, 277, 276, 275, 274, 273, 272, 271, 270, 269, 268, 267, 266, 265, 264, 263, 262, 261, 260, 259, 258, 257, 256, 255, 254, 253, 252, 251, 250, 249, 248, 247, 246, 245, 244, 243, 242, 241, 240, 239, 238, 237, 236, 235, 234, 233, 232, 231, 230, 229, 228, 227, 226, 225, 224, 223, 222, 221, 220, 219, 218, 217, 216, 215, 214, 213, 212, 211, 210, 209, 208, 207, 206, 205, 204, 203, 202, 201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191, 190, 189, 188, 187, 186, 185, 184, 183, 182, 181, 180, 179, 178, 177, 176, 175, 174, 173, 172, 171, 170, 169, 168, 167, 166, 165, 164, 163, 162, 161, 160, 159, 158, 157, 156, 155, 154, 153, 152, 151, 150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)
#define __BITS_NUM_ARGS2(N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N11, N12, N13, N14, N15, N16, N17, N18, N19, N20, N21, N22, N23, N24, N25, N26, N27, N28, N29, N30, N31, N32, N33, N34, N35, N36, N37, N38, N39, N40, N41, N42, N43, N44, N45, N46, N47, N48, N49, N50, N51, N52, N53, N54, N55, N56, N57, N58, N59, N60, N61, N62, N63, N64, N65, N66, N67, N68, N69, N70, N71, N72, N73, N74, N75, N76, N77, N78, N79, N80, N81, N82, N83, N84, N85, N86, N87, N88, N89, N90, N91, N92, N93, N94, N95, N96, N97, N98, N99, N100, N101, N102, N103, N104, N105, N106, N107, N108, N109, N110, N111, N112, N113, N114, N115, N116, N117, N118, N119, N120, N121, N122, N123, N124, N125, N126, N127, N128, N129, N130, N131, N132, N133, N134, N135, N136, N137, N138, N139, N140, N141, N142, N143, N144, N145, N146, N147, N148, N149, N150, N151, N152, N153, N154, N155, N156, N157, N158, N159, N160, N161, N162, N163, N164, N165, N166, N167, N168, N169, N170, N171, N172, N173, N174, N175, N176, N177, N178, N179, N180, N181, N182, N183, N184, N185, N186, N187, N188, N189, N190, N191, N192, N193, N194, N195, N196, N197, N198, N199, N200, N201, N202, N203, N204, N205, N206, N207, N208, N209, N210, N211, N212, N213, N214, N215, N216, N217, N218, N219, N220, N221, N222, N223, N224, N225, N226, N227, N228, N229, N230, N231, N232, N233, N234, N235, N236, N237, N238, N239, N240, N241, N242, N243, N244, N245, N246, N247, N248, N249, N250, N251, N252, N253, N254, N255, N256, N257, N258, N259, N260, N261, N262, N263, N264, N265, N266, N267, N268, N269, N270, N271, N272, N273, N274, N275, N276, N277, N278, N279, N280, N281, N282, N283, N284, N285, N286, N287, N288, N289, N290, N291, N292, N293, N294, N295, N296, N297, N298, N299, N300, N301, N302, N303, N304, N305, N306, N307, N308, N309, N310, N311, N312, N313, N314, N315, N316, N317, N318, N319, N320, N321, N322, N323, N324, N325, N326, N327, N328, N329, N330, N331, N332, N333, N334, N335, N336, N337, N338, N339, N340, N341, N342, N343, N344, N345, N346, N347, N348, N349, N350, N351, N352, N353, N354, N355, N356, N357, N358, N359, N360, N361, N362, N363, N364, N365, N366, N367, N368, N369, N370, N371, N372, N373, N374, N375, N376, N377, N378, N379, N380, N381, N382, N383, N384, N385, N386, N387, N388, N389, N390, N391, N392, N393, N394, N395, N396, N397, N398, N399, N400, N401, N402, N403, N404, N405, N406, N407, N408, N409, N410, N411, N412, N413, N414, N415, N416, N417, N418, N419, N420, N421, N422, N423, N424, N425, N426, N427, N428, N429, N430, N431, N432, N433, N434, N435, N436, N437, N438, N439, N440, N441, N442, N443, N444, N445, N446, N447, N448, N449, N450, N451, N452, N453, N454, N455, N456, N457, N458, N459, N460, N461, N462, N463, N464, N465, N466, N467, N468, N469, N470, N471, N472, N473, N474, N475, N476, N477, N478, N479, N480, N481, N482, N483, N484, N485, N486, N487, N488, N489, N490, N491, N492, N493, N494, N495, N496, N497, N498, N499, N500, N501, N502, N503, N504, N505, N506, N507, N508, N509, N510, N511, N512, N, ...) N


// Recurse macros
#define __BITS_RECURSE_PAIR(func, ...)                          __BITS_DO2(__BITS_PAIR,   __BITS_NUM_ARGS(__VA_ARGS__))(func, __VA_ARGS__)
#define __BITS_RECURSE_SINGLE(func, sep, nameSpace, name, ...)  __BITS_DO2(__BITS_SINGLE, __BITS_NUM_ARGS(__VA_ARGS__))(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_DO2(func, N) __BITS_DO3(func, N)
#define __BITS_DO3(func, N) func ## _ ## N

// Recursively call a macro with a pair of arguments
#define __BITS_PAIR_2(  func, a, b)       func(a, b)
#define __BITS_PAIR_4(  func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_2(  func, __VA_ARGS__)
#define __BITS_PAIR_6(  func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_4(  func, __VA_ARGS__)
#define __BITS_PAIR_8(  func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_6(  func, __VA_ARGS__)
#define __BITS_PAIR_10( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_8(  func, __VA_ARGS__)
#define __BITS_PAIR_12( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_10( func, __VA_ARGS__)
#define __BITS_PAIR_14( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_12( func, __VA_ARGS__)
#define __BITS_PAIR_16( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_14( func, __VA_ARGS__)
#define __BITS_PAIR_18( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_16( func, __VA_ARGS__)
#define __BITS_PAIR_20( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_18( func, __VA_ARGS__)
#define __BITS_PAIR_22( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_20( func, __VA_ARGS__)
#define __BITS_PAIR_24( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_22( func, __VA_ARGS__)
#define __BITS_PAIR_26( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_24( func, __VA_ARGS__)
#define __BITS_PAIR_28( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_26( func, __VA_ARGS__)
#define __BITS_PAIR_30( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_28( func, __VA_ARGS__)
#define __BITS_PAIR_32( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_30( func, __VA_ARGS__)
#define __BITS_PAIR_34( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_32( func, __VA_ARGS__)
#define __BITS_PAIR_36( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_34( func, __VA_ARGS__)
#define __BITS_PAIR_38( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_36( func, __VA_ARGS__)
#define __BITS_PAIR_40( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_38( func, __VA_ARGS__)
#define __BITS_PAIR_42( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_40( func, __VA_ARGS__)
#define __BITS_PAIR_44( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_42( func, __VA_ARGS__)
#define __BITS_PAIR_46( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_44( func, __VA_ARGS__)
#define __BITS_PAIR_48( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_46( func, __VA_ARGS__)
#define __BITS_PAIR_50( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_48( func, __VA_ARGS__)
#define __BITS_PAIR_52( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_50( func, __VA_ARGS__)
#define __BITS_PAIR_54( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_52( func, __VA_ARGS__)
#define __BITS_PAIR_56( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_54( func, __VA_ARGS__)
#define __BITS_PAIR_58( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_56( func, __VA_ARGS__)
#define __BITS_PAIR_60( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_58( func, __VA_ARGS__)
#define __BITS_PAIR_62( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_60( func, __VA_ARGS__)
#define __BITS_PAIR_64( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_62( func, __VA_ARGS__)
#define __BITS_PAIR_66( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_64( func, __VA_ARGS__)
#define __BITS_PAIR_68( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_66( func, __VA_ARGS__)
#define __BITS_PAIR_70( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_68( func, __VA_ARGS__)
#define __BITS_PAIR_72( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_70( func, __VA_ARGS__)
#define __BITS_PAIR_74( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_72( func, __VA_ARGS__)
#define __BITS_PAIR_76( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_74( func, __VA_ARGS__)
#define __BITS_PAIR_78( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_76( func, __VA_ARGS__)
#define __BITS_PAIR_80( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_78( func, __VA_ARGS__)
#define __BITS_PAIR_82( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_80( func, __VA_ARGS__)
#define __BITS_PAIR_84( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_82( func, __VA_ARGS__)
#define __BITS_PAIR_86( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_84( func, __VA_ARGS__)
#define __BITS_PAIR_88( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_86( func, __VA_ARGS__)
#define __BITS_PAIR_90( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_88( func, __VA_ARGS__)
#define __BITS_PAIR_92( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_90( func, __VA_ARGS__)
#define __BITS_PAIR_94( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_92( func, __VA_ARGS__)
#define __BITS_PAIR_96( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_94( func, __VA_ARGS__)
#define __BITS_PAIR_98( func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_96( func, __VA_ARGS__)
#define __BITS_PAIR_100(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_98( func, __VA_ARGS__)
#define __BITS_PAIR_102(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_100(func, __VA_ARGS__)
#define __BITS_PAIR_104(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_102(func, __VA_ARGS__)
#define __BITS_PAIR_106(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_104(func, __VA_ARGS__)
#define __BITS_PAIR_108(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_106(func, __VA_ARGS__)
#define __BITS_PAIR_110(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_108(func, __VA_ARGS__)
#define __BITS_PAIR_112(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_110(func, __VA_ARGS__)
#define __BITS_PAIR_114(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_112(func, __VA_ARGS__)
#define __BITS_PAIR_116(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_114(func, __VA_ARGS__)
#define __BITS_PAIR_118(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_116(func, __VA_ARGS__)
#define __BITS_PAIR_120(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_118(func, __VA_ARGS__)
#define __BITS_PAIR_122(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_120(func, __VA_ARGS__)
#define __BITS_PAIR_124(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_122(func, __VA_ARGS__)
#define __BITS_PAIR_126(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_124(func, __VA_ARGS__)
#define __BITS_PAIR_128(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_126(func, __VA_ARGS__)
#define __BITS_PAIR_130(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_128(func, __VA_ARGS__)
#define __BITS_PAIR_132(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_130(func, __VA_ARGS__)
#define __BITS_PAIR_134(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_132(func, __VA_ARGS__)
#define __BITS_PAIR_136(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_134(func, __VA_ARGS__)
#define __BITS_PAIR_138(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_136(func, __VA_ARGS__)
#define __BITS_PAIR_140(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_138(func, __VA_ARGS__)
#define __BITS_PAIR_142(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_140(func, __VA_ARGS__)
#define __BITS_PAIR_144(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_142(func, __VA_ARGS__)
#define __BITS_PAIR_146(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_144(func, __VA_ARGS__)
#define __BITS_PAIR_148(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_146(func, __VA_ARGS__)
#define __BITS_PAIR_150(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_148(func, __VA_ARGS__)
#define __BITS_PAIR_152(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_150(func, __VA_ARGS__)
#define __BITS_PAIR_154(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_152(func, __VA_ARGS__)
#define __BITS_PAIR_156(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_154(func, __VA_ARGS__)
#define __BITS_PAIR_158(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_156(func, __VA_ARGS__)
#define __BITS_PAIR_160(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_158(func, __VA_ARGS__)
#define __BITS_PAIR_162(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_160(func, __VA_ARGS__)
#define __BITS_PAIR_164(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_162(func, __VA_ARGS__)
#define __BITS_PAIR_166(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_164(func, __VA_ARGS__)
#define __BITS_PAIR_168(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_166(func, __VA_ARGS__)
#define __BITS_PAIR_170(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_168(func, __VA_ARGS__)
#define __BITS_PAIR_172(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_170(func, __VA_ARGS__)
#define __BITS_PAIR_174(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_172(func, __VA_ARGS__)
#define __BITS_PAIR_176(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_174(func, __VA_ARGS__)
#define __BITS_PAIR_178(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_176(func, __VA_ARGS__)
#define __BITS_PAIR_180(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_178(func, __VA_ARGS__)
#define __BITS_PAIR_182(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_180(func, __VA_ARGS__)
#define __BITS_PAIR_184(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_182(func, __VA_ARGS__)
#define __BITS_PAIR_186(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_184(func, __VA_ARGS__)
#define __BITS_PAIR_188(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_186(func, __VA_ARGS__)
#define __BITS_PAIR_190(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_188(func, __VA_ARGS__)
#define __BITS_PAIR_192(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_190(func, __VA_ARGS__)
#define __BITS_PAIR_194(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_192(func, __VA_ARGS__)
#define __BITS_PAIR_196(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_194(func, __VA_ARGS__)
#define __BITS_PAIR_198(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_196(func, __VA_ARGS__)
#define __BITS_PAIR_200(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_198(func, __VA_ARGS__)
#define __BITS_PAIR_202(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_200(func, __VA_ARGS__)
#define __BITS_PAIR_204(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_202(func, __VA_ARGS__)
#define __BITS_PAIR_206(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_204(func, __VA_ARGS__)
#define __BITS_PAIR_208(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_206(func, __VA_ARGS__)
#define __BITS_PAIR_210(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_208(func, __VA_ARGS__)
#define __BITS_PAIR_212(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_210(func, __VA_ARGS__)
#define __BITS_PAIR_214(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_212(func, __VA_ARGS__)
#define __BITS_PAIR_216(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_214(func, __VA_ARGS__)
#define __BITS_PAIR_218(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_216(func, __VA_ARGS__)
#define __BITS_PAIR_220(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_218(func, __VA_ARGS__)
#define __BITS_PAIR_222(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_220(func, __VA_ARGS__)
#define __BITS_PAIR_224(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_222(func, __VA_ARGS__)
#define __BITS_PAIR_226(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_224(func, __VA_ARGS__)
#define __BITS_PAIR_228(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_226(func, __VA_ARGS__)
#define __BITS_PAIR_230(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_228(func, __VA_ARGS__)
#define __BITS_PAIR_232(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_230(func, __VA_ARGS__)
#define __BITS_PAIR_234(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_232(func, __VA_ARGS__)
#define __BITS_PAIR_236(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_234(func, __VA_ARGS__)
#define __BITS_PAIR_238(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_236(func, __VA_ARGS__)
#define __BITS_PAIR_240(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_238(func, __VA_ARGS__)
#define __BITS_PAIR_242(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_240(func, __VA_ARGS__)
#define __BITS_PAIR_244(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_242(func, __VA_ARGS__)
#define __BITS_PAIR_246(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_244(func, __VA_ARGS__)
#define __BITS_PAIR_248(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_246(func, __VA_ARGS__)
#define __BITS_PAIR_250(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_248(func, __VA_ARGS__)
#define __BITS_PAIR_252(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_250(func, __VA_ARGS__)
#define __BITS_PAIR_254(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_252(func, __VA_ARGS__)
#define __BITS_PAIR_256(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_254(func, __VA_ARGS__)
#define __BITS_PAIR_258(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_256(func, __VA_ARGS__)
#define __BITS_PAIR_260(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_258(func, __VA_ARGS__)
#define __BITS_PAIR_262(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_260(func, __VA_ARGS__)
#define __BITS_PAIR_264(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_262(func, __VA_ARGS__)
#define __BITS_PAIR_266(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_264(func, __VA_ARGS__)
#define __BITS_PAIR_268(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_266(func, __VA_ARGS__)
#define __BITS_PAIR_270(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_268(func, __VA_ARGS__)
#define __BITS_PAIR_272(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_270(func, __VA_ARGS__)
#define __BITS_PAIR_274(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_272(func, __VA_ARGS__)
#define __BITS_PAIR_276(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_274(func, __VA_ARGS__)
#define __BITS_PAIR_278(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_276(func, __VA_ARGS__)
#define __BITS_PAIR_280(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_278(func, __VA_ARGS__)
#define __BITS_PAIR_282(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_280(func, __VA_ARGS__)
#define __BITS_PAIR_284(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_282(func, __VA_ARGS__)
#define __BITS_PAIR_286(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_284(func, __VA_ARGS__)
#define __BITS_PAIR_288(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_286(func, __VA_ARGS__)
#define __BITS_PAIR_290(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_288(func, __VA_ARGS__)
#define __BITS_PAIR_292(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_290(func, __VA_ARGS__)
#define __BITS_PAIR_294(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_292(func, __VA_ARGS__)
#define __BITS_PAIR_296(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_294(func, __VA_ARGS__)
#define __BITS_PAIR_298(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_296(func, __VA_ARGS__)
#define __BITS_PAIR_300(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_298(func, __VA_ARGS__)
#define __BITS_PAIR_302(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_300(func, __VA_ARGS__)
#define __BITS_PAIR_304(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_302(func, __VA_ARGS__)
#define __BITS_PAIR_306(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_304(func, __VA_ARGS__)
#define __BITS_PAIR_308(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_306(func, __VA_ARGS__)
#define __BITS_PAIR_310(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_308(func, __VA_ARGS__)
#define __BITS_PAIR_312(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_310(func, __VA_ARGS__)
#define __BITS_PAIR_314(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_312(func, __VA_ARGS__)
#define __BITS_PAIR_316(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_314(func, __VA_ARGS__)
#define __BITS_PAIR_318(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_316(func, __VA_ARGS__)
#define __BITS_PAIR_320(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_318(func, __VA_ARGS__)
#define __BITS_PAIR_322(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_320(func, __VA_ARGS__)
#define __BITS_PAIR_324(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_322(func, __VA_ARGS__)
#define __BITS_PAIR_326(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_324(func, __VA_ARGS__)
#define __BITS_PAIR_328(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_326(func, __VA_ARGS__)
#define __BITS_PAIR_330(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_328(func, __VA_ARGS__)
#define __BITS_PAIR_332(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_330(func, __VA_ARGS__)
#define __BITS_PAIR_334(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_332(func, __VA_ARGS__)
#define __BITS_PAIR_336(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_334(func, __VA_ARGS__)
#define __BITS_PAIR_338(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_336(func, __VA_ARGS__)
#define __BITS_PAIR_340(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_338(func, __VA_ARGS__)
#define __BITS_PAIR_342(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_340(func, __VA_ARGS__)
#define __BITS_PAIR_344(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_342(func, __VA_ARGS__)
#define __BITS_PAIR_346(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_344(func, __VA_ARGS__)
#define __BITS_PAIR_348(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_346(func, __VA_ARGS__)
#define __BITS_PAIR_350(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_348(func, __VA_ARGS__)
#define __BITS_PAIR_352(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_350(func, __VA_ARGS__)
#define __BITS_PAIR_354(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_352(func, __VA_ARGS__)
#define __BITS_PAIR_356(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_354(func, __VA_ARGS__)
#define __BITS_PAIR_358(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_356(func, __VA_ARGS__)
#define __BITS_PAIR_360(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_358(func, __VA_ARGS__)
#define __BITS_PAIR_362(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_360(func, __VA_ARGS__)
#define __BITS_PAIR_364(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_362(func, __VA_ARGS__)
#define __BITS_PAIR_366(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_364(func, __VA_ARGS__)
#define __BITS_PAIR_368(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_366(func, __VA_ARGS__)
#define __BITS_PAIR_370(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_368(func, __VA_ARGS__)
#define __BITS_PAIR_372(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_370(func, __VA_ARGS__)
#define __BITS_PAIR_374(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_372(func, __VA_ARGS__)
#define __BITS_PAIR_376(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_374(func, __VA_ARGS__)
#define __BITS_PAIR_378(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_376(func, __VA_ARGS__)
#define __BITS_PAIR_380(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_378(func, __VA_ARGS__)
#define __BITS_PAIR_382(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_380(func, __VA_ARGS__)
#define __BITS_PAIR_384(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_382(func, __VA_ARGS__)
#define __BITS_PAIR_386(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_384(func, __VA_ARGS__)
#define __BITS_PAIR_388(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_386(func, __VA_ARGS__)
#define __BITS_PAIR_390(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_388(func, __VA_ARGS__)
#define __BITS_PAIR_392(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_390(func, __VA_ARGS__)
#define __BITS_PAIR_394(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_392(func, __VA_ARGS__)
#define __BITS_PAIR_396(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_394(func, __VA_ARGS__)
#define __BITS_PAIR_398(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_396(func, __VA_ARGS__)
#define __BITS_PAIR_400(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_398(func, __VA_ARGS__)
#define __BITS_PAIR_402(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_400(func, __VA_ARGS__)
#define __BITS_PAIR_404(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_402(func, __VA_ARGS__)
#define __BITS_PAIR_406(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_404(func, __VA_ARGS__)
#define __BITS_PAIR_408(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_406(func, __VA_ARGS__)
#define __BITS_PAIR_410(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_408(func, __VA_ARGS__)
#define __BITS_PAIR_412(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_410(func, __VA_ARGS__)
#define __BITS_PAIR_414(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_412(func, __VA_ARGS__)
#define __BITS_PAIR_416(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_414(func, __VA_ARGS__)
#define __BITS_PAIR_418(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_416(func, __VA_ARGS__)
#define __BITS_PAIR_420(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_418(func, __VA_ARGS__)
#define __BITS_PAIR_422(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_420(func, __VA_ARGS__)
#define __BITS_PAIR_424(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_422(func, __VA_ARGS__)
#define __BITS_PAIR_426(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_424(func, __VA_ARGS__)
#define __BITS_PAIR_428(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_426(func, __VA_ARGS__)
#define __BITS_PAIR_430(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_428(func, __VA_ARGS__)
#define __BITS_PAIR_432(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_430(func, __VA_ARGS__)
#define __BITS_PAIR_434(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_432(func, __VA_ARGS__)
#define __BITS_PAIR_436(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_434(func, __VA_ARGS__)
#define __BITS_PAIR_438(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_436(func, __VA_ARGS__)
#define __BITS_PAIR_440(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_438(func, __VA_ARGS__)
#define __BITS_PAIR_442(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_440(func, __VA_ARGS__)
#define __BITS_PAIR_444(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_442(func, __VA_ARGS__)
#define __BITS_PAIR_446(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_444(func, __VA_ARGS__)
#define __BITS_PAIR_448(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_446(func, __VA_ARGS__)
#define __BITS_PAIR_450(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_448(func, __VA_ARGS__)
#define __BITS_PAIR_452(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_450(func, __VA_ARGS__)
#define __BITS_PAIR_454(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_452(func, __VA_ARGS__)
#define __BITS_PAIR_456(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_454(func, __VA_ARGS__)
#define __BITS_PAIR_458(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_456(func, __VA_ARGS__)
#define __BITS_PAIR_460(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_458(func, __VA_ARGS__)
#define __BITS_PAIR_462(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_460(func, __VA_ARGS__)
#define __BITS_PAIR_464(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_462(func, __VA_ARGS__)
#define __BITS_PAIR_466(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_464(func, __VA_ARGS__)
#define __BITS_PAIR_468(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_466(func, __VA_ARGS__)
#define __BITS_PAIR_470(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_468(func, __VA_ARGS__)
#define __BITS_PAIR_472(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_470(func, __VA_ARGS__)
#define __BITS_PAIR_474(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_472(func, __VA_ARGS__)
#define __BITS_PAIR_476(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_474(func, __VA_ARGS__)
#define __BITS_PAIR_478(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_476(func, __VA_ARGS__)
#define __BITS_PAIR_480(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_478(func, __VA_ARGS__)
#define __BITS_PAIR_482(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_480(func, __VA_ARGS__)
#define __BITS_PAIR_484(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_482(func, __VA_ARGS__)
#define __BITS_PAIR_486(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_484(func, __VA_ARGS__)
#define __BITS_PAIR_488(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_486(func, __VA_ARGS__)
#define __BITS_PAIR_490(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_488(func, __VA_ARGS__)
#define __BITS_PAIR_492(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_490(func, __VA_ARGS__)
#define __BITS_PAIR_494(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_492(func, __VA_ARGS__)
#define __BITS_PAIR_496(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_494(func, __VA_ARGS__)
#define __BITS_PAIR_498(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_496(func, __VA_ARGS__)
#define __BITS_PAIR_500(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_498(func, __VA_ARGS__)
#define __BITS_PAIR_502(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_500(func, __VA_ARGS__)
#define __BITS_PAIR_504(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_502(func, __VA_ARGS__)
#define __BITS_PAIR_506(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_504(func, __VA_ARGS__)
#define __BITS_PAIR_508(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_506(func, __VA_ARGS__)
#define __BITS_PAIR_510(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_508(func, __VA_ARGS__)
#define __BITS_PAIR_512(func, a, b, ...)  __BITS_PAIR_2(func, a, b) , __BITS_PAIR_510(func, __VA_ARGS__)

// Recursively call a macro with a single argument (ignoring the second one)
#define __BITS_SINGLE_2(  func, sep, nameSpace, name, a, b)       func(nameSpace, name, a)
#define __BITS_SINGLE_4(  func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_2(  func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_6(  func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_4(  func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_8(  func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_6(  func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_10( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_8(  func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_12( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_10( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_14( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_12( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_16( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_14( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_18( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_16( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_20( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_18( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_22( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_20( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_24( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_22( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_26( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_24( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_28( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_26( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_30( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_28( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_32( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_30( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_34( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_32( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_36( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_34( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_38( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_36( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_40( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_38( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_42( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_40( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_44( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_42( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_46( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_44( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_48( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_46( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_50( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_48( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_52( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_50( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_54( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_52( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_56( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_54( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_58( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_56( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_60( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_58( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_62( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_60( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_64( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_62( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_66( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_64( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_68( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_66( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_70( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_68( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_72( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_70( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_74( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_72( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_76( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_74( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_78( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_76( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_80( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_78( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_82( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_80( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_84( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_82( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_86( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_84( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_88( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_86( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_90( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_88( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_92( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_90( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_94( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_92( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_96( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_94( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_98( func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_96( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_100(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_98( func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_102(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_100(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_104(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_102(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_106(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_104(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_108(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_106(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_110(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_108(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_112(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_110(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_114(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_112(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_116(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_114(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_118(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_116(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_120(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_118(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_122(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_120(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_124(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_122(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_126(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_124(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_128(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_126(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_130(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_128(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_132(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_130(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_134(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_132(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_136(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_134(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_138(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_136(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_140(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_138(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_142(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_140(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_144(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_142(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_146(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_144(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_148(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_146(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_150(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_148(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_152(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_150(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_154(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_152(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_156(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_154(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_158(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_156(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_160(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_158(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_162(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_160(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_164(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_162(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_166(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_164(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_168(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_166(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_170(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_168(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_172(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_170(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_174(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_172(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_176(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_174(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_178(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_176(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_180(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_178(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_182(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_180(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_184(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_182(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_186(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_184(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_188(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_186(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_190(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_188(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_192(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_190(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_194(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_192(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_196(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_194(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_198(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_196(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_200(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_198(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_202(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_200(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_204(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_202(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_206(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_204(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_208(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_206(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_210(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_208(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_212(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_210(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_214(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_212(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_216(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_214(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_218(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_216(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_220(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_218(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_222(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_220(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_224(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_222(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_226(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_224(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_228(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_226(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_230(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_228(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_232(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_230(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_234(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_232(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_236(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_234(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_238(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_236(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_240(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_238(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_242(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_240(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_244(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_242(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_246(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_244(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_248(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_246(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_250(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_248(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_252(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_250(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_254(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_252(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_256(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_254(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_258(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_256(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_260(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_258(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_262(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_260(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_264(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_262(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_266(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_264(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_268(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_266(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_270(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_268(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_272(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_270(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_274(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_272(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_276(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_274(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_278(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_276(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_280(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_278(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_282(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_280(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_284(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_282(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_286(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_284(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_288(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_286(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_290(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_288(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_292(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_290(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_294(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_292(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_296(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_294(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_298(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_296(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_300(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_298(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_302(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_300(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_304(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_302(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_306(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_304(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_308(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_306(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_310(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_308(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_312(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_310(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_314(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_312(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_316(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_314(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_318(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_316(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_320(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_318(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_322(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_320(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_324(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_322(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_326(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_324(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_328(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_326(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_330(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_328(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_332(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_330(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_334(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_332(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_336(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_334(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_338(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_336(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_340(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_338(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_342(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_340(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_344(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_342(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_346(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_344(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_348(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_346(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_350(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_348(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_352(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_350(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_354(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_352(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_356(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_354(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_358(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_356(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_360(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_358(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_362(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_360(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_364(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_362(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_366(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_364(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_368(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_366(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_370(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_368(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_372(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_370(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_374(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_372(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_376(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_374(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_378(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_376(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_380(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_378(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_382(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_380(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_384(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_382(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_386(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_384(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_388(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_386(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_390(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_388(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_392(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_390(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_394(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_392(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_396(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_394(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_398(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_396(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_400(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_398(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_402(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_400(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_404(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_402(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_406(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_404(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_408(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_406(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_410(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_408(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_412(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_410(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_414(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_412(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_416(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_414(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_418(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_416(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_420(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_418(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_422(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_420(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_424(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_422(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_426(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_424(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_428(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_426(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_430(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_428(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_432(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_430(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_434(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_432(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_436(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_434(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_438(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_436(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_440(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_438(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_442(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_440(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_444(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_442(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_446(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_444(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_448(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_446(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_450(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_448(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_452(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_450(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_454(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_452(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_456(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_454(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_458(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_456(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_460(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_458(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_462(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_460(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_464(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_462(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_466(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_464(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_468(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_466(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_470(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_468(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_472(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_470(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_474(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_472(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_476(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_474(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_478(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_476(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_480(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_478(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_482(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_480(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_484(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_482(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_486(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_484(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_488(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_486(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_490(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_488(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_492(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_490(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_494(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_492(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_496(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_494(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_498(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_496(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_500(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_498(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_502(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_500(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_504(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_502(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_506(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_504(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_508(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_506(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_510(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_508(func, sep, nameSpace, name, __VA_ARGS__)
#define __BITS_SINGLE_512(func, sep, nameSpace, name, a, b, ...)  __BITS_SINGLE_2(func, sep, nameSpace, name, a, b) sep __BITS_SINGLE_510(func, sep, nameSpace, name, __VA_ARGS__)

#endif /* BITS_DETAIL_HELPER_MACROS_H */
